/*
 * File: app/view/Main.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Contact.view.Main', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.main',

    requires: [
        'Contact.view.List',
        'Contact.view.FavoriteView'
    ],

    config: {
        tabBar: {
            border: '',
            docked: 'bottom',
            layout: {
                pack: 'center',
                type: 'hbox'
            }
        },
        items: [
            {
                xtype: 'contactlist',
                title: 'Contatos',
                iconCls: 'user'
            },
            {
                xtype: 'favoriteview',
                title: 'Favoritos',
                iconCls: 'favorites'
            },
            {
                xtype: 'toolbar',
                docked: 'top',
                items: [
                    {
                        xtype: 'button',
                        cls: 'square',
                        itemId: 'addContactBtn',
                        ui: 'action-round',
                        iconCls: 'add',
                        text: 'Criar Contato'
                    },
                    {
                        xtype: 'label',
                        flex: 1
                    },
                    {
                        xtype: 'button',
                        itemId: 'logoutbtn',
                        iconCls: 'action',
                        text: 'Sair'
                    }
                ]
            }
        ]
    }

});