/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({
    models: [
        'Contact'
    ],
    stores: [
        'ContactStore'
    ],
    views: [
        'Main',
        'Info',
        'Form',
        'Picture',
        'List',
        'FavoriteView',
        'Login',
        'MyViewport'
    ],
    requires: [
        'Ext.MessageBox',
        'Ext.device.Camera',
        'Ext.field.Email',
        'Ext.field.Number',
        'Ext.form.FieldSet',
        'Ext.field.Password',
        'Ext.util.DelayedTask',
        'Ext.Label'
    ],
    controllers: [
        'Contacts',
        'Login',
        'iOS7'
    ],
    name: 'Contact',

    launch: function() {
        // Ajuste toolbar quando for iOS 7
        if (Ext.os.is.iOS && Ext.os.version.major >= 7) {
          Ext.select(".x-toolbar").applyStyles("height: 62px; padding-top: 15px;");
        }


        Ext.util.Format.empty = function(value, defaultValue) {
            return !Ext.isEmpty(value) ? value : defaultValue;
        };
        Ext.util.Format.undef = function(value, defaultValue) {
            return Ext.isDefined(value) ? value : defaultValue;
        };
        var ds = Ext.StoreMgr.lookup('ContactStore');

        ds.setProxy({
            type: 'sqlitestorage',
            dbConfig: {
                tablename: 'contatos',
                dbConn: Ext.DbConnection
            },
            model: 'Contact.model.Contact'
        });

        ds.load();
        Ext.create('Contact.view.MyViewport', {fullscreen: true});
    }

});
